import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState} from 'react'

export default function Home() {
// need state for form input 
const [formInput, setFormInput] = useState('')

// state for return pokemon
const [pokemon, setPokemon ] = useState(null)

// loading state 
const [isLoading, setIsLoading] = useState(false)

// error state 
const [isError, setIsError] = useState(false)

// need change handler for input feild 
const handleChange = (event)=> {
setFormInput(event.target.value)
event.preventDefault
}

// need onSubmit function for form
const handleSubmit = (event)=> {
  // we want to use fetch to hit our pokemon api 
  event.preventDefault()
  setIsLoading(true)
  setIsError(false)
  setPokemon(null)
  fetch(`https://pokeapi.co/api/v2/pokemon/${formInput}`)
  .then((response) => response.json())
  .then((data) => setPokemon(data))
  .catch((error)=> {
    setIsError(true)
  })
  
  setIsLoading(false)
  setFormInput('')
  
 
}
console.log('poke', pokemon)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Who you fightin ? 
        </h1>
        <br></br> 

        <form onSubmit={handleSubmit}>
          <label htmlFor="pokemon-search">POKEMON SEARCH</label>
          <input type="text" id="pokemon-search" name="pokemon-search" value={formInput} onChange={handleChange} />
          <button type='submit' >Submit</button> 
        </form> 

        <br></br> 

        {pokemon ? <div>
        <p> You sure you can handle them?</p>
              <p>{pokemon.species.name}</p> 
              <img style={{height: 200, width:200}} alt='' src={pokemon.sprites.front_default}/> 
              </div> 
        : <p> ... find your foe...</p> }

        {isLoading ? <p>Telling them you trying to catch these hands</p> : null }
        {isError ? <p> uh oh something went wrong</p> : null}

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
